/******************************************************************************/
/*                 Generated by IBExpert 23/10/2022 18:40:00                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE LANCAMENTO_ABASTECIMENTO (
    ID_BOMBA          INTEGER NOT NULL,
    LITROS_ABASTECER  DOUBLE PRECISION NOT NULL,
    VALOR_COBRADO     DOUBLE PRECISION NOT NULL,
    IMPOSTO_PERC      DOUBLE PRECISION NOT NULL,
    DATA_HORA         TIMESTAMP NOT NULL
);



/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE LANCAMENTO_ABASTECIMENTO ADD CONSTRAINT FK_LANCAMENTO_ABASTECIMENTO_1 FOREIGN KEY (ID_BOMBA) REFERENCES BOMBAS (ID_BOMBA);


/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
