object frmbaseInheritable: TfrmbaseInheritable
  Left = 0
  Top = 0
  Caption = 'frmbaseInheritable'
  ClientHeight = 507
  ClientWidth = 769
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = [fsBold]
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 16
end
